name: BileTools
version: 2
main: com.volmit.bile.BileTools
api-version: 1.13

commands:
  biletools:
    aliases: [bile]

permissions:
  bile.use:
    description: Gives access to biletools
    default: op